# Generated by Django 4.1.1 on 2022-10-12 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post_job',
        ),
    ]
