# Generated by Django 4.1.1 on 2022-10-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_delete_post_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('cemail', models.EmailField(max_length=254)),
                ('ctitle', models.CharField(max_length=50)),
                ('ctype', models.CharField(choices=[('remote', 'remote'), ('hybrid', 'hybrid')], max_length=30)),
                ('cexp', models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('4-5', '4-5'), ('5-6', '5-6'), ('6-7', '6-7'), ('7-8', '7-8')], max_length=30)),
                ('jtype', models.CharField(choices=[('partime', 'partime'), ('fulltime', 'fulltime')], max_length=30)),
            ],
        ),
    ]
