# Generated by Django 4.1.1 on 2022-10-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_jobpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_logmodel',
        ),
    ]
